import {Product} from '../assets/interfaces/product';
export const products:Product[]=[
    {
        name:"Frametory, 11x14 Black Picture Frames ",
        link:"https://www.amazon.com/Frametory-11x14-Black-Picture-Frame/dp/B071F7Z9K6/ref=sr_1_14?dchild=1&keywords=picture&qid=1614594693&sr=8-14",
        description:"Frametory, 11x14 Black Picture Frames - Made to Display Pictures 8x10 with Mat or 11x14 Without Mat - Wide Molding - Pre-Installed Wall Mounting Hardware (Black)",
        image:"https://m.media-amazon.com/images/I/71+3UXouZhL._AC_UL640_QL65_.jpg",
        price:"$15.99",
        rating:5,
        id:0,
        categoryId:0,
        likesCount:35,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Americanflat",
        link:"https://www.amazon.com/Americanflat-10-Piece-Multi-Frames-Gallery/dp/B079P4LFRJ/ref=sr_1_1?dchild=1&keywords=picture&qid=1614594693&sr=8-1",
        description:"Americanflat 10-Piece Black Picture Frame Set | Includes Sizes 8x10, 5x7, and 4x6. Shatter-Resistant Glass. Hanging Hardware Included!",
        image:"https://m.media-amazon.com/images/I/81CgZuwXbjL._AC_UL640_QL65_.jpg",
        price:"$17.99",
        rating:5,
        id:1,
        categoryId:0,
        likesCount:12,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"PA Plus Classic Black",
        link:"https://www.amazon.com/Classic-Frames-matted-Polystyrene-Hanging/dp/B08B3KZKTR/ref=sr_1_40?dchild=1&keywords=picture&qid=1614594693&sr=8-40",
        description:"A Plus Classic Black 20”x24” Photo Frames matted to 16”x20” Photos, Polystyrene Glass for Wall Hanging",
        image:"https://m.media-amazon.com/images/I/81HBOt5YtpL._AC_UL640_QL65_.jpg",
        price:"$28.99",
        rating:3,
        id:2,
        categoryId:0,
        likesCount:56,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Mud Road in Pink Forest Bright Lines",
        link:"https://www.amazon.com/Americanflat-11x14-Collage-Picture-Frame/dp/B018T7GK2C/ref=sr_1_46?dchild=1&keywords=picture&qid=1614594693&sr=8-46",
        description:"Americanflat 11x14 Collage Picture Frame in Black with Five 4x6 Picture Displays - Shatter Resistant Glass Horizontal and Vertical Formats for Wall (MW1114BK546)",
        image:"https://m.media-amazon.com/images/I/81c32QH+U8L._AC_UL640_QL65_.jpg",
        price:"$42.99",
        rating:4,
        id:3,
        categoryId:0,
        likesCount:96,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Ophanie",
        link:"https://www.amazon.com/Ophanie-Picture-High-Definition-Plexiglass-Tabletop/dp/B089281P32/ref=sr_1_31?dchild=1&keywords=picture&qid=1614594693&sr=8-31",
        description:"Ophanie 8x10 Picture Frames Set of 5, Easy Setup Photo Frame with 5x7 Mat and High-Definition Plexiglass for Wall or Tabletop Display, Black",
        image:"https://m.media-amazon.com/images/I/715FJE2f4wL._AC_UL640_QL65_.jpg",
        price:"$22.99",
        rating:4,
        id:4,
        categoryId:0,
        likesCount:86,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"The Library",
        link:"https://www.amazon.com/Library-James-W-P-Campbell/dp/022609281X/ref=sr_1_14?crid=CO13IGGC3XV&dchild=1&keywords=library&qid=1614610132&sprefix=Libra%2Caps%2C370&sr=8-14",
        description:"The Library: A World History Hardcover – Illustrated, October 14, 2013",
        image:"https://m.media-amazon.com/images/I/81gnUK9MTUL._AC_UL640_QL65_.jpg",
        price:"$41.52",
        rating:4,
        id:5,
        categoryId:2,
        likesCount:152,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"The Four Winds",
        link:"https://www.amazon.com/dp/1250178606/ref=s9_acsd_hps_bw_c2_x_0_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=3JXKA1XJYWF68HRCH0PS&pf_rd_t=101&pf_rd_p=470172df-5407-46ff-9f06-227fa8d65c5d&pf_rd_i=283155",
        description:"The Four Winds: A Novel Hardcover – February 2, 2021",
        image:"https://images-na.ssl-images-amazon.com/images/I/51r9ZiBU6rL._AC_SX184_.jpg",
        price:"$17.39",
        rating:4,
        id:6,
        categoryId:2,
        likesCount:65,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"My Brilliant Life",
        link:"https://www.amazon.com/dp/1250750555/ref=s9_acsd_hps_bw_c2_x_5_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=3JXKA1XJYWF68HRCH0PS&pf_rd_t=101&pf_rd_p=470172df-5407-46ff-9f06-227fa8d65c5d&pf_rd_i=283155",
        description:"A BEST OF THE MONTH SELECTION BY OPRAH MAGAZINE",
        image:"https://images-na.ssl-images-amazon.com/images/I/51JEKxwYhfL._AC_SX368_.jpg",
        price:"$16.65",
        rating:5,
        id:7,
        categoryId:2,
        likesCount:45,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"A Desolation Called Peace",
        link:"https://www.amazon.com/dp/1250186463/ref=s9_acsd_hps_bw_c2_x_3_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=3JXKA1XJYWF68HRCH0PS&pf_rd_t=101&pf_rd_p=470172df-5407-46ff-9f06-227fa8d65c5d&pf_rd_i=283155",
        description:"An all around brilliant space opera, I absolutely love it.―Ann Leckie, on A Memory Called Empire",
        image:"https://images-na.ssl-images-amazon.com/images/I/51ucj27xFCL._AC_SX368_.jpg",
        price:"$17.45",
        rating:1,
        id:8,
        categoryId:2,
        likesCount:87,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"A Court of Silver Flames",
        link:"https://www.amazon.com/dp/168119628X/ref=s9_acsd_hps_bw_c2_x_1_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=3JXKA1XJYWF68HRCH0PS&pf_rd_t=101&pf_rd_p=470172df-5407-46ff-9f06-227fa8d65c5d&pf_rd_i=283155",
        description:"Sarah J. Maas's sexy, richly imagined series continues with the journey of Feyre's fiery sister, Nesta.",
        image:"https://images-na.ssl-images-amazon.com/images/I/51SFgFBhDsL._AC_SX368_.jpg",
        price:"$16.80",
        rating:3,
        id:9,
        categoryId:2,
        likesCount:36,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Maroon 5 - Live at Casino de Paris",
        link:"https://www.amazon.com/Maroon-Casino-Paris-Adam-Levine/dp/B07TTV8321/ref=sr_1_6?dchild=1&keywords=music&qid=1615019619&sr=8-6",
        description:"Adam Levine and Maroon 5 perform their hits including 'She Will Be Loved', 'This Love' and 'Harder To Breathe' live at the Casino de Paris in 2011.",
        image:"https://m.media-amazon.com/images/I/71uqTSgP6wL._AC_UY436_QL65_.jpg",
        price:"$9.99",
        rating:5,
        id:10,
        categoryId:1,
        likesCount:214,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Vivaldi's Four Seasons With Breathtaking Views",
        link:"https://www.amazon.com/Vivaldi-Four-Seasons-Relaxation-Nature/dp/B071F1NTG6/ref=sr_1_11?dchild=1&keywords=music&qid=1615019619&sr=8-11",
        description:"Sharecare Windows presents Symphony Squares' Antonio Vivaldi's the Fours Seasons. Composed in 1723, this set of 4 violin concertos propose an early form of descriptive music. Winter makes prominent use of pizzicato, whereas summer evokes a storm in its final movement.",
        image:"https://m.media-amazon.com/images/I/71DfR4vvWSL._AC_UY436_QL65_.jpg",
        price:"$2.99",
        rating:3,
        id:11,
        categoryId:1,
        likesCount:42,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Fleetwood Mac: Rumours (Classic Albums)",
        link:"https://www.amazon.com/Fleetwood-Mac-Rumours-Classic-Albums/dp/B07JM211PL/ref=sr_1_13?dchild=1&keywords=music&qid=1615019619&sr=8-13",
        description:"Fleetwood Mac's hugely successful album Rumours has sold over 40 million copies worldwide, was christened Album of the Year at the 1978 Grammy Awards and quickly earned its place in the pantheon of rock music history. ",
        image:"https://m.media-amazon.com/images/I/713tAQ27rFL._AC_UY436_QL65_.jpg",
        price:"Free Download",
        rating:4,
        id:12,
        categoryId:1,
        likesCount:60,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Country Music Today",
        link:"https://www.amazon.com/Cynogage-Country-Music-Today/dp/B07MVL46PW/ref=sr_1_16?dchild=1&keywords=music&qid=1615019619&sr=8-16",
        description:"Country Music",
        image:"https://m.media-amazon.com/images/I/41eU6k76KgL._AC_UY436_QL65_.png",
        price:"Free Download",
        rating:5,
        id:13,
        categoryId:1,
        likesCount:60,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Country Music Today",
        link:"https://www.amazon.com/Hello-Sir-Dear/dp/B0789VVC4F/ref=sr_1_17?dchild=1&keywords=music&qid=1615019619&sr=8-17",
        description:"Bollywood Music Videos",
        image:"https://m.media-amazon.com/images/I/71EIWiALHSL._AC_UY436_QL65_.jpg",
        price:"Free Download",
        rating:3,
        id:14,
        categoryId:1,
        likesCount:123,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"CSpalding NBA Zi/O Indoor-Outdoor 29.5 Basketbal",
        link:"https://www.amazon.com/Spalding-NBA-Indoor-Outdoor-Basketball/dp/B000A7OUE0/ref=sr_1_3?crid=17LA8KBAUFCY2&dchild=1&keywords=basketball&qid=1615020942&s=sporting-goods&sprefix=bass%2Csporting-intl-ship%2C350&sr=1-3",
        description:"Official NBA size and weight: Size 7, 29.5 inch",
        image:"https://m.media-amazon.com/images/I/A1ser-udbFL._AC_UL640_QL65_.jpg",
        price:"$34.99",
        rating:4,
        id:15,
        categoryId:3,
        likesCount:75,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"PISIQI Knee Compression Pads Long Leg Sleeve Brace Protection for Basketball, Football & Volleyball (2 Sleeves)",
        link:"https://www.amazon.com/PISIQI-Compression-Protection-Basketball-Volleyball/dp/B07NTNCL9Q/ref=sr_1_28_sspa?crid=17LA8KBAUFCY2&dchild=1&keywords=basketball&qid=1615020942&s=sporting-goods&sprefix=bass%2Csporting-intl-ship%2C350&sr=1-28-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzOEZOTzlOOUNFWlZJJmVuY3J5cHRlZElkPUEwMTIwNDE4OVhZNVVXQ0tOSU5aJmVuY3J5cHRlZEFkSWQ9QTAxMzYxNDkyVE8wNTgySUI1QldVJndpZGdldE5hbWU9c3BfYnRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==",
        description:"KNEE COMPRESSION SLEEVES MATERIAL: Knee sleeves(2 pcs) offer premium softness and wicking ability using elastic polyester fabric",
        image:"https://m.media-amazon.com/images/I/51n6ZRh1FVL._AC_UL640_QL65_.jpg",
        price:"$12.99",
        rating:3,
        id:16,
        categoryId:3,
        likesCount:25,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Spalding NBA Street Outdoor Basketball",
        link:"https://www.amazon.com/Spalding-NBA-Street-Basketball-Official/dp/B0009VELG4/ref=sr_1_1?crid=17LA8KBAUFCY2&dchild=1&keywords=basketball&qid=1615020942&s=sporting-goods&sprefix=bass%2Csporting-intl-ship%2C350&sr=1-1",
        description:"Performance: Durable outdoor rubber cover",
        image:"https://m.media-amazon.com/images/I/91PlxEj64+L._AC_UL640_QL65_.jpg",
        price:"$17.99",
        rating:5,
        id:17,
        categoryId:3,
        likesCount:93,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Spalding NBA Street Phantom Outdoor Basketball",
        link:"https://www.amazon.com/Spalding-Street-Phantom-Basketball-29-5/dp/B00UVQ3V1I/ref=sr_1_2?crid=17LA8KBAUFCY2&dchild=1&keywords=basketball&qid=1615020942&s=sporting-goods&sprefix=bass%2Csporting-intl-ship%2C350&sr=1-2",
        description:"Official NBA size and weight: Size 7, 29.5 inches",
        image:"https://m.media-amazon.com/images/I/91SS9XoXHyL._AC_UL640_QL65_.jpg",
        price:"$15.89",
        rating:4,
        id:18,
        categoryId:3,
        likesCount:59,
        isLiked:false,
        isRemoved:false
    },
    {
        name:"Spalding NBA Instinct Basketball, Orange/Black/Oatmeal, Size 7 (29.5-Inch)",
        link:"https://www.amazon.com/Spalding-Instinct-Basketball-Oatmeal-29-5-Inch/dp/B00UJCXHH2/ref=sr_1_25?crid=17LA8KBAUFCY2&dchild=1&keywords=basketball&qid=1615020942&s=sporting-goods&sprefix=bass%2Csporting-intl-ship%2C350&sr=1-25",
        description:"Premium composite cover",
        image:"https://m.media-amazon.com/images/I/91kY3nFG-DL._AC_UL640_QL65_.jpg",
        price:"$21.25",
        rating:5,
        id:19,
        categoryId:3,
        likesCount:86,
        isLiked:false,
        isRemoved:false
    }
];
